package com.mio.netmusic.bean

import kotlinx.serialization.Serializable

@Serializable
data class Playlist(
    val adType: Int?,
    val anonimous: Boolean?,
    val artists: String?,
    val backgroundCoverId: Long?,
    val backgroundCoverUrl: String?,
    val cloudTrackCount: Int?,
    val commentThreadId: String?,
    val containsTracks: Boolean?,
    val copied: Boolean?,
    val coverImgId: Long?,
    val coverImgId_str: String?,
    val coverImgUrl: String?,
    val createTime: Long?,
    val creator: Creator?,
    val description: String?,
    val englishTitle: String?,
    val highQuality: Boolean?,
    val id: Long?,
    val name: String?,
    val newImported: Boolean?,
    val opRecommend: Boolean?,
    val ordered: Boolean?,
    val playCount: Long?,
    val privacy: Int?,
    val recommendInfo: RecommendInfo?,
    val shareStatus: String?,
    val sharedUsers: String?,
    val specialType: Int?,
    val status: Int?,
    val subscribed: Boolean,
    val subscribedCount: Int?,
    val subscribers: List<String?>?,
    val tags: List<String?>?,
    val titleImage: Long?,
    val titleImageUrl: String?,
    val top: Boolean?,
    val totalDuration: Int?,
    val trackCount: Int?,
    val trackNumberUpdateTime: Long?,
    val trackUpdateTime: Long?,
    val tracks: String?,
    val updateFrequency: String?,
    val updateTime: Long?,
    val userId: Int?
)